
"""
Tests: src/python/structure.py
"""

import mdtraj
import numpy as np
from numpy.testing import (assert_almost_equal, assert_array_almost_equal,
                           assert_allclose, assert_array_equal)
                           
from scipy import ndimage

from thor import structure
from thor import math2
from thor.testing import skip, ref_file


class TestAtomicToDensity(object):

    # @skip
    # def test_atomic_to_density_1():
    #     
    #     grid_dimensions = (25,) * 3
    #     grid_spacing    = 0.5
    #     traj = mdtraj.load(ref_file('pentagon.pdb'))
    #     
    #     # Reference generated by CCTBX : mmtbx.real_space.sampled_model_density()
    #     ref = np.load(ref_file('density_square.npy'))
    #     #ref /= ref.max()
    #     
    #     tst1 = structure.atomic_to_density(traj, grid_dimensions, 
    #                                        grid_spacing, radial_cutoff=3.0)
    #     #tst1 /= tst1.max()
    #     tst2 = structure.atomic_to_density(traj, grid_dimensions, 
    #                                        grid_spacing, radial_cutoff=None)
    #     #tst2 /= tst2.max()
    #                              
    #     from matplotlib import pyplot as plt
    #     
    #     
    #     
    #     # plt.figure()
    #     # plt.scatter(ref, tst1)
    #     # plt.show()
    #     
    #     
    #     # NEXT STEP IS TO VISUALIZE BOTH
    #     from mayavi import mlab
    #     mlab.contour3d(ref, transparent=True)
    #     mlab.contour3d(tst1, transparent=True)
    #     mlab.show()
    #     
    #                              
    #     assert_allclose(ref, tst1)

    def test_atomic_to_density_positions(self):
        # ensure the atoms are in the right spot
    
        traj = mdtraj.load(ref_file('pentagon.pdb'))
        atomic_positions = traj.xyz[0] * 10.0
        #print atomic_positions
        
        # permutation that matches the results, manually coded = :'(
        pi = np.array([4, 3, 1, 0, 2]) 
    
        for spcg in [0.25, 0.5, 1.0]:
            
            grid = structure.atomic_to_density(traj, (51,)*3, spcg)
            
            maxima = math2.find_local_maxima(grid)
            grid_maxima  = np.array(maxima).astype(np.float).T
            grid_maxima -= (np.array(grid.shape) / 2 + 1.0)[None,:] # center around origin
            grid_maxima *= spcg                                     # apply correct scale
            
            grid_maxima = grid_maxima[pi]
            
            #print grid_maxima - atomic_positions
            err = np.sum(np.abs(grid_maxima - atomic_positions)) / spcg
            assert err < 5.0, 'maxima found in estimated density map do not ' \
                              'match atomic positions in original model'
    

    def test_atomic_to_density_consistency(self):
        # Make sure changing the grid spacing parameters doesnt change the results
    
        traj = mdtraj.load(ref_file('pentagon.pdb'))
    
        tst1 = structure.atomic_to_density(traj, (25,) *3, 0.2)
        tst2 = structure.atomic_to_density(traj, (51,)*3, 0.1)
    
        R = np.corrcoef(tst1.flatten(), tst2[1::2,1::2,1::2].flatten())[0,1]
        assert R > 0.9
    
    
    