# instructions for the Travis CI build system

language: python
python:
  - 3.7

before_install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  - conda create -q -n thor python=$TRAVIS_PYTHON_VERSION
  - conda install -n thor numexpr numpy scipy matplotlib pytables pyyaml cython pytest --yes
  - conda install -n thor --channel omnia mdtraj --yes
  - conda install -n thor --channel conda-forge pyfftw fabio --yes
  - source activate test-environment
  - python setup.py install

env:
  - TESTFOLDER=test
  - TESTFOLDER=test/scatter
  - TESTFOLDER=test/xray/test_xray.py
  - TESTFOLDER=test/xray/test_xray2.py

# Run tests
script:
  - pytest "$TESTFOLDER"

